### ISSUE TITLE
Not defined files (A_28cells.npy and C_28cells.npy)

### ISSUE THREAD

**Issue by Dana162001** [klarman-cell-observatory/PowerAnalysisForSpatialOmics#6]
In osmfish_cortex/osmfish_generation.ipynb notebook in the Composite Graph section there are 2 files A_28cells.npy and C_28cells.npy which are used as adjacency matrix and circle center positions resepcevly. However, it is not clear where are those files coming from or how were they generated. Therefore it is difficult to proceed with the analysis of our own data. Could you please share some details about how can one get those files? 

Thank you in advance!

**Comment by AasrithaNallapu** [comment]
Hi, 
I am trying to implement your analysis with your data, and am facing the same issue with the A_28cells.npy and C_28cells.npy files. I used the 2 files that were provided in the sample_results folder, but this yeilds some differences in the results in the NB_Cell_Discov_clean.ipynb notebook. 
Sharing a bit more details on what these files are and where they are generated from would help in proceeding with our analysis. Thank you.

**Comment by eschrom** [comment]
Similar issue here, although I am trying to create my own circle packing rather than follow the osmfish_cortex example. I can run random_circle_packing.py and tune parameters like -x, -y, --rmin, and --rmax just fine. However, any output directory that I specify via -o is ignored, and no A.npy or C.npy files are created. Instead, I just get two .png images of the graph and the voronoi, both inside my working directory. From these images, it's clear the random circle packing is working, but without A.npy and C.npy, I can't continue on to the cell labeling step.
